name: Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Clawboy would this affect?
      options:
        - Smart Contracts (apps/contracts)
        - MCP Server (apps/mcp-server)
        - Indexer (apps/indexer)
        - Web App (apps/web)
        - MCP Client (packages/mcp-client)
        - OpenClaw Skill (packages/openclaw-skill)
        - New Package/App
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is this related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: dropdown
    id: contribution
    attributes:
      label: Would you be willing to contribute this?
      options:
        - "Yes, I'd like to implement this"
        - 'Yes, with guidance'
        - 'No, but I can help test'
        - 'No'

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this hasn't been requested
          required: true
